### ISSUE TITLE
Unit tests and Quicklisp

### ISSUE THREAD

**Issue by phoe** [ndantam/sycamore#1]
Hey!

Do you have any kind of unit tests written for this?

If yes, then did you consider making an issue on https://github.com/quicklisp/quicklisp-projects/ to get this added to Quicklisp?

~phoe

**Comment by ndantam** [comment]
There are some test cases in `./share/test/` and `./src/fuzz-test.lisp`.  It does randomized testing of the weighted-tree structure (some of the set operations and the array leaves optimization get rather hairy).

I suppose this could go into quicklisp.  I just haven't gotten around to making that happen, yet.

**Comment by avodonosov** [comment]
https://github.com/quicklisp/quicklisp-projects/issues/1431

**Comment by avodonosov** [comment]
Fails to build on Quicklisp: https://github.com/quicklisp/quicklisp-projects/issues/1431#issuecomment-360912298

**Comment by ndantam** [comment]
Build on SBCL 1.4.3 fixed in 3b115df

**Comment by avodonosov** [comment]
Released on quicklisp - close the issue?

**Comment by phoe** [comment]
Very yes.
