### ISSUE TITLE
Key cannot be found after insertion even though comparer returns 0

### ISSUE THREAD

**Issue by simendsjo** [ndantam/sycamore#6]
I'm converting from fset to sycamore because I need the performance, but I'm hitting a problem which might look related to sycamore.

To find the problem, I try to look up every value I insert after inserting it. I then fetch the comparer and checks that it returns 0 as they are equal to avoid a false positive where the equal function is wrong. The key is a cons of a fixnum and a clim:standard-point, e.g. `(0 . #<CLIM:STANDARD-POINT 0 7>)`, but I've seen it for other things where the keys are lists of plain symbols too.

The code below prints `(0 . #<STANDARD-POINT 0 7>) not found, but comparer says 0`

I write here before investigating further in case I've misunderstood something obvious.

```lisp
(defun with (map key value)
  (let ((result (sycamore:tree-map-insert map key value)))
    (test-map result)
    result))
```

```lisp
(defun test-map (map)
  (declare (optimize (debug 3)))
  (dolist (key (sycamore:tree-map-keys map) map)
    (unless (sycamore:tree-map-contains map key)
      (let* ((comparer (sycamore::tree-map-compare map))
             (comp (funcall comparer (cons (copy key) 'foo) (cons (copy key) 'bar))))
        (format t "~A not found, but comparer says ~A~%" key comp)
        (break)))))
```

EDIT: This is using SBCL 2.3.7 on Linux 6.6.6.
EDIT2: The value is added and visible when I inspect the map.

**Comment by ndantam** [comment]
Is it possible that the provided compare function is not a total order on the set of keys?  If the compare function is not a total order, then you might get elements inserted into the wrong place and/or be unable to find elements in the tree, which I think could produce the behavior you see (a key/value is in the tree, but `tree-map-contains` can't find it).

If you could provide a complete test case, I will try to reproduce.

**Comment by simendsjo** [comment]
Thanks! A point in the right direction. The problem wasn't total ordering, but that I piggy-backed on `fset:compare-lexicographically` for lists (called `fset:compare` rather than a recursive call), and it didn't properly support nested lists.

Hacked together a quick check myself, and now everything works!

```lisp
(labels ((compare (a b)
           (if (or (atom a) (atom b))
               (fset:compare a b)
               (ecase (compare (car a) (car b))
                 (:less :less)
                 (:greater :greater)
                 (:equal (compare (cdr a) (cdr b)))))))
           (ecase (compare akey bkey)
             (:less -1)
             (:greater 1)
             (:equal 0)))
```
